language: python
python:
  - "2.7"
services:
  - redis-server
cache:
  - pip
  - apt
before_install: cp mining/mining.sample.ini mining/mining.ini
install: make environment
script: make test
notifications:
  irc: "irc.freenode.org#openmining"
  on_success: "never"
